// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DrawMessageProto.proto

package com.zzz.game.proto;

public final class DrawMessageProto {
  private DrawMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.zzz.game.proto.LoginReq}
   */
  public static final class LoginReq extends
      com.google.protobuf.GeneratedMessage
      implements LoginReqOrBuilder {
    // Use LoginReq.newBuilder() to construct.
    private LoginReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginReq defaultInstance;
    public static LoginReq getDefaultInstance() {
      return defaultInstance;
    }

    public LoginReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_LoginReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_LoginReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zzz.game.proto.DrawMessageProto.LoginReq.class, com.zzz.game.proto.DrawMessageProto.LoginReq.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginReq> PARSER =
        new com.google.protobuf.AbstractParser<LoginReq>() {
      public LoginReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zzz.game.proto.DrawMessageProto.LoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zzz.game.proto.DrawMessageProto.LoginReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zzz.game.proto.LoginReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zzz.game.proto.DrawMessageProto.LoginReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_LoginReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_LoginReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zzz.game.proto.DrawMessageProto.LoginReq.class, com.zzz.game.proto.DrawMessageProto.LoginReq.Builder.class);
      }

      // Construct using com.zzz.game.proto.DrawMessageProto.LoginReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_LoginReq_descriptor;
      }

      public com.zzz.game.proto.DrawMessageProto.LoginReq getDefaultInstanceForType() {
        return com.zzz.game.proto.DrawMessageProto.LoginReq.getDefaultInstance();
      }

      public com.zzz.game.proto.DrawMessageProto.LoginReq build() {
        com.zzz.game.proto.DrawMessageProto.LoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zzz.game.proto.DrawMessageProto.LoginReq buildPartial() {
        com.zzz.game.proto.DrawMessageProto.LoginReq result = new com.zzz.game.proto.DrawMessageProto.LoginReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zzz.game.proto.DrawMessageProto.LoginReq) {
          return mergeFrom((com.zzz.game.proto.DrawMessageProto.LoginReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zzz.game.proto.DrawMessageProto.LoginReq other) {
        if (other == com.zzz.game.proto.DrawMessageProto.LoginReq.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zzz.game.proto.DrawMessageProto.LoginReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zzz.game.proto.DrawMessageProto.LoginReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zzz.game.proto.LoginReq)
    }

    static {
      defaultInstance = new LoginReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zzz.game.proto.LoginReq)
  }

  public interface LoginRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code com.zzz.game.proto.LoginResp}
   */
  public static final class LoginResp extends
      com.google.protobuf.GeneratedMessage
      implements LoginRespOrBuilder {
    // Use LoginResp.newBuilder() to construct.
    private LoginResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginResp defaultInstance;
    public static LoginResp getDefaultInstance() {
      return defaultInstance;
    }

    public LoginResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_LoginResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_LoginResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zzz.game.proto.DrawMessageProto.LoginResp.class, com.zzz.game.proto.DrawMessageProto.LoginResp.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginResp> PARSER =
        new com.google.protobuf.AbstractParser<LoginResp>() {
      public LoginResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zzz.game.proto.DrawMessageProto.LoginResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zzz.game.proto.DrawMessageProto.LoginResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zzz.game.proto.DrawMessageProto.LoginResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zzz.game.proto.LoginResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zzz.game.proto.DrawMessageProto.LoginRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_LoginResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_LoginResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zzz.game.proto.DrawMessageProto.LoginResp.class, com.zzz.game.proto.DrawMessageProto.LoginResp.Builder.class);
      }

      // Construct using com.zzz.game.proto.DrawMessageProto.LoginResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_LoginResp_descriptor;
      }

      public com.zzz.game.proto.DrawMessageProto.LoginResp getDefaultInstanceForType() {
        return com.zzz.game.proto.DrawMessageProto.LoginResp.getDefaultInstance();
      }

      public com.zzz.game.proto.DrawMessageProto.LoginResp build() {
        com.zzz.game.proto.DrawMessageProto.LoginResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zzz.game.proto.DrawMessageProto.LoginResp buildPartial() {
        com.zzz.game.proto.DrawMessageProto.LoginResp result = new com.zzz.game.proto.DrawMessageProto.LoginResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zzz.game.proto.DrawMessageProto.LoginResp) {
          return mergeFrom((com.zzz.game.proto.DrawMessageProto.LoginResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zzz.game.proto.DrawMessageProto.LoginResp other) {
        if (other == com.zzz.game.proto.DrawMessageProto.LoginResp.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zzz.game.proto.DrawMessageProto.LoginResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zzz.game.proto.DrawMessageProto.LoginResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zzz.game.proto.LoginResp)
    }

    static {
      defaultInstance = new LoginResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zzz.game.proto.LoginResp)
  }

  public interface DrawLineReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.zzz.game.proto.DrawLineReq.point points = 1;
    /**
     * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
     */
    java.util.List<com.zzz.game.proto.DrawMessageProto.DrawLineReq.point> 
        getPointsList();
    /**
     * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
     */
    com.zzz.game.proto.DrawMessageProto.DrawLineReq.point getPoints(int index);
    /**
     * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
     */
    int getPointsCount();
    /**
     * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
     */
    java.util.List<? extends com.zzz.game.proto.DrawMessageProto.DrawLineReq.pointOrBuilder> 
        getPointsOrBuilderList();
    /**
     * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
     */
    com.zzz.game.proto.DrawMessageProto.DrawLineReq.pointOrBuilder getPointsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.zzz.game.proto.DrawLineReq}
   */
  public static final class DrawLineReq extends
      com.google.protobuf.GeneratedMessage
      implements DrawLineReqOrBuilder {
    // Use DrawLineReq.newBuilder() to construct.
    private DrawLineReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DrawLineReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DrawLineReq defaultInstance;
    public static DrawLineReq getDefaultInstance() {
      return defaultInstance;
    }

    public DrawLineReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DrawLineReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                points_ = new java.util.ArrayList<com.zzz.game.proto.DrawMessageProto.DrawLineReq.point>();
                mutable_bitField0_ |= 0x00000001;
              }
              points_.add(input.readMessage(com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          points_ = java.util.Collections.unmodifiableList(points_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_DrawLineReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_DrawLineReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zzz.game.proto.DrawMessageProto.DrawLineReq.class, com.zzz.game.proto.DrawMessageProto.DrawLineReq.Builder.class);
    }

    public static com.google.protobuf.Parser<DrawLineReq> PARSER =
        new com.google.protobuf.AbstractParser<DrawLineReq>() {
      public DrawLineReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DrawLineReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DrawLineReq> getParserForType() {
      return PARSER;
    }

    public interface pointOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 x = 1;
      /**
       * <code>required int32 x = 1;</code>
       */
      boolean hasX();
      /**
       * <code>required int32 x = 1;</code>
       */
      int getX();

      // required int32 y = 2;
      /**
       * <code>required int32 y = 2;</code>
       */
      boolean hasY();
      /**
       * <code>required int32 y = 2;</code>
       */
      int getY();
    }
    /**
     * Protobuf type {@code com.zzz.game.proto.DrawLineReq.point}
     */
    public static final class point extends
        com.google.protobuf.GeneratedMessage
        implements pointOrBuilder {
      // Use point.newBuilder() to construct.
      private point(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private point(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final point defaultInstance;
      public static point getDefaultInstance() {
        return defaultInstance;
      }

      public point getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private point(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                x_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                y_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_DrawLineReq_point_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_DrawLineReq_point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.class, com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.Builder.class);
      }

      public static com.google.protobuf.Parser<point> PARSER =
          new com.google.protobuf.AbstractParser<point>() {
        public point parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new point(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<point> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 x = 1;
      public static final int X_FIELD_NUMBER = 1;
      private int x_;
      /**
       * <code>required int32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }

      // required int32 y = 2;
      public static final int Y_FIELD_NUMBER = 2;
      private int y_;
      /**
       * <code>required int32 y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }

      private void initFields() {
        x_ = 0;
        y_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasX()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasY()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, y_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, y_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.zzz.game.proto.DrawMessageProto.DrawLineReq.point parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zzz.game.proto.DrawMessageProto.DrawLineReq.point parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zzz.game.proto.DrawMessageProto.DrawLineReq.point parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zzz.game.proto.DrawMessageProto.DrawLineReq.point parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zzz.game.proto.DrawMessageProto.DrawLineReq.point parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.zzz.game.proto.DrawMessageProto.DrawLineReq.point parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.zzz.game.proto.DrawMessageProto.DrawLineReq.point parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.zzz.game.proto.DrawMessageProto.DrawLineReq.point parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.zzz.game.proto.DrawMessageProto.DrawLineReq.point parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.zzz.game.proto.DrawMessageProto.DrawLineReq.point parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.zzz.game.proto.DrawMessageProto.DrawLineReq.point prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.zzz.game.proto.DrawLineReq.point}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.zzz.game.proto.DrawMessageProto.DrawLineReq.pointOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_DrawLineReq_point_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_DrawLineReq_point_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.class, com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.Builder.class);
        }

        // Construct using com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          x_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          y_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_DrawLineReq_point_descriptor;
        }

        public com.zzz.game.proto.DrawMessageProto.DrawLineReq.point getDefaultInstanceForType() {
          return com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.getDefaultInstance();
        }

        public com.zzz.game.proto.DrawMessageProto.DrawLineReq.point build() {
          com.zzz.game.proto.DrawMessageProto.DrawLineReq.point result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.zzz.game.proto.DrawMessageProto.DrawLineReq.point buildPartial() {
          com.zzz.game.proto.DrawMessageProto.DrawLineReq.point result = new com.zzz.game.proto.DrawMessageProto.DrawLineReq.point(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.x_ = x_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.y_ = y_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.zzz.game.proto.DrawMessageProto.DrawLineReq.point) {
            return mergeFrom((com.zzz.game.proto.DrawMessageProto.DrawLineReq.point)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.zzz.game.proto.DrawMessageProto.DrawLineReq.point other) {
          if (other == com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.getDefaultInstance()) return this;
          if (other.hasX()) {
            setX(other.getX());
          }
          if (other.hasY()) {
            setY(other.getY());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasX()) {
            
            return false;
          }
          if (!hasY()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.zzz.game.proto.DrawMessageProto.DrawLineReq.point parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.zzz.game.proto.DrawMessageProto.DrawLineReq.point) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 x = 1;
        private int x_ ;
        /**
         * <code>required int32 x = 1;</code>
         */
        public boolean hasX() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public int getX() {
          return x_;
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public Builder setX(int value) {
          bitField0_ |= 0x00000001;
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public Builder clearX() {
          bitField0_ = (bitField0_ & ~0x00000001);
          x_ = 0;
          onChanged();
          return this;
        }

        // required int32 y = 2;
        private int y_ ;
        /**
         * <code>required int32 y = 2;</code>
         */
        public boolean hasY() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public int getY() {
          return y_;
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public Builder setY(int value) {
          bitField0_ |= 0x00000002;
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public Builder clearY() {
          bitField0_ = (bitField0_ & ~0x00000002);
          y_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.zzz.game.proto.DrawLineReq.point)
      }

      static {
        defaultInstance = new point(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.zzz.game.proto.DrawLineReq.point)
    }

    // repeated .com.zzz.game.proto.DrawLineReq.point points = 1;
    public static final int POINTS_FIELD_NUMBER = 1;
    private java.util.List<com.zzz.game.proto.DrawMessageProto.DrawLineReq.point> points_;
    /**
     * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
     */
    public java.util.List<com.zzz.game.proto.DrawMessageProto.DrawLineReq.point> getPointsList() {
      return points_;
    }
    /**
     * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
     */
    public java.util.List<? extends com.zzz.game.proto.DrawMessageProto.DrawLineReq.pointOrBuilder> 
        getPointsOrBuilderList() {
      return points_;
    }
    /**
     * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
     */
    public int getPointsCount() {
      return points_.size();
    }
    /**
     * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
     */
    public com.zzz.game.proto.DrawMessageProto.DrawLineReq.point getPoints(int index) {
      return points_.get(index);
    }
    /**
     * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
     */
    public com.zzz.game.proto.DrawMessageProto.DrawLineReq.pointOrBuilder getPointsOrBuilder(
        int index) {
      return points_.get(index);
    }

    private void initFields() {
      points_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPointsCount(); i++) {
        if (!getPoints(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < points_.size(); i++) {
        output.writeMessage(1, points_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < points_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, points_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zzz.game.proto.DrawMessageProto.DrawLineReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzz.game.proto.DrawMessageProto.DrawLineReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzz.game.proto.DrawMessageProto.DrawLineReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzz.game.proto.DrawMessageProto.DrawLineReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzz.game.proto.DrawMessageProto.DrawLineReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zzz.game.proto.DrawMessageProto.DrawLineReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zzz.game.proto.DrawMessageProto.DrawLineReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zzz.game.proto.DrawMessageProto.DrawLineReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zzz.game.proto.DrawMessageProto.DrawLineReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zzz.game.proto.DrawMessageProto.DrawLineReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zzz.game.proto.DrawMessageProto.DrawLineReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zzz.game.proto.DrawLineReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zzz.game.proto.DrawMessageProto.DrawLineReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_DrawLineReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_DrawLineReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zzz.game.proto.DrawMessageProto.DrawLineReq.class, com.zzz.game.proto.DrawMessageProto.DrawLineReq.Builder.class);
      }

      // Construct using com.zzz.game.proto.DrawMessageProto.DrawLineReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPointsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pointsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zzz.game.proto.DrawMessageProto.internal_static_com_zzz_game_proto_DrawLineReq_descriptor;
      }

      public com.zzz.game.proto.DrawMessageProto.DrawLineReq getDefaultInstanceForType() {
        return com.zzz.game.proto.DrawMessageProto.DrawLineReq.getDefaultInstance();
      }

      public com.zzz.game.proto.DrawMessageProto.DrawLineReq build() {
        com.zzz.game.proto.DrawMessageProto.DrawLineReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zzz.game.proto.DrawMessageProto.DrawLineReq buildPartial() {
        com.zzz.game.proto.DrawMessageProto.DrawLineReq result = new com.zzz.game.proto.DrawMessageProto.DrawLineReq(this);
        int from_bitField0_ = bitField0_;
        if (pointsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            points_ = java.util.Collections.unmodifiableList(points_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.points_ = points_;
        } else {
          result.points_ = pointsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zzz.game.proto.DrawMessageProto.DrawLineReq) {
          return mergeFrom((com.zzz.game.proto.DrawMessageProto.DrawLineReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zzz.game.proto.DrawMessageProto.DrawLineReq other) {
        if (other == com.zzz.game.proto.DrawMessageProto.DrawLineReq.getDefaultInstance()) return this;
        if (pointsBuilder_ == null) {
          if (!other.points_.isEmpty()) {
            if (points_.isEmpty()) {
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePointsIsMutable();
              points_.addAll(other.points_);
            }
            onChanged();
          }
        } else {
          if (!other.points_.isEmpty()) {
            if (pointsBuilder_.isEmpty()) {
              pointsBuilder_.dispose();
              pointsBuilder_ = null;
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pointsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPointsFieldBuilder() : null;
            } else {
              pointsBuilder_.addAllMessages(other.points_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPointsCount(); i++) {
          if (!getPoints(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zzz.game.proto.DrawMessageProto.DrawLineReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zzz.game.proto.DrawMessageProto.DrawLineReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.zzz.game.proto.DrawLineReq.point points = 1;
      private java.util.List<com.zzz.game.proto.DrawMessageProto.DrawLineReq.point> points_ =
        java.util.Collections.emptyList();
      private void ensurePointsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          points_ = new java.util.ArrayList<com.zzz.game.proto.DrawMessageProto.DrawLineReq.point>(points_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.zzz.game.proto.DrawMessageProto.DrawLineReq.point, com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.Builder, com.zzz.game.proto.DrawMessageProto.DrawLineReq.pointOrBuilder> pointsBuilder_;

      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public java.util.List<com.zzz.game.proto.DrawMessageProto.DrawLineReq.point> getPointsList() {
        if (pointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(points_);
        } else {
          return pointsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public int getPointsCount() {
        if (pointsBuilder_ == null) {
          return points_.size();
        } else {
          return pointsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public com.zzz.game.proto.DrawMessageProto.DrawLineReq.point getPoints(int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);
        } else {
          return pointsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public Builder setPoints(
          int index, com.zzz.game.proto.DrawMessageProto.DrawLineReq.point value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.set(index, value);
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public Builder setPoints(
          int index, com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public Builder addPoints(com.zzz.game.proto.DrawMessageProto.DrawLineReq.point value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public Builder addPoints(
          int index, com.zzz.game.proto.DrawMessageProto.DrawLineReq.point value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(index, value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public Builder addPoints(
          com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public Builder addPoints(
          int index, com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public Builder addAllPoints(
          java.lang.Iterable<? extends com.zzz.game.proto.DrawMessageProto.DrawLineReq.point> values) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          super.addAll(values, points_);
          onChanged();
        } else {
          pointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public Builder clearPoints() {
        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public Builder removePoints(int index) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.remove(index);
          onChanged();
        } else {
          pointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.Builder getPointsBuilder(
          int index) {
        return getPointsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public com.zzz.game.proto.DrawMessageProto.DrawLineReq.pointOrBuilder getPointsOrBuilder(
          int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);  } else {
          return pointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public java.util.List<? extends com.zzz.game.proto.DrawMessageProto.DrawLineReq.pointOrBuilder> 
           getPointsOrBuilderList() {
        if (pointsBuilder_ != null) {
          return pointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(points_);
        }
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.Builder addPointsBuilder() {
        return getPointsFieldBuilder().addBuilder(
            com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.getDefaultInstance());
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.Builder addPointsBuilder(
          int index) {
        return getPointsFieldBuilder().addBuilder(
            index, com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.getDefaultInstance());
      }
      /**
       * <code>repeated .com.zzz.game.proto.DrawLineReq.point points = 1;</code>
       */
      public java.util.List<com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.Builder> 
           getPointsBuilderList() {
        return getPointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zzz.game.proto.DrawMessageProto.DrawLineReq.point, com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.Builder, com.zzz.game.proto.DrawMessageProto.DrawLineReq.pointOrBuilder> 
          getPointsFieldBuilder() {
        if (pointsBuilder_ == null) {
          pointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.zzz.game.proto.DrawMessageProto.DrawLineReq.point, com.zzz.game.proto.DrawMessageProto.DrawLineReq.point.Builder, com.zzz.game.proto.DrawMessageProto.DrawLineReq.pointOrBuilder>(
                  points_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          points_ = null;
        }
        return pointsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.zzz.game.proto.DrawLineReq)
    }

    static {
      defaultInstance = new DrawLineReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zzz.game.proto.DrawLineReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzz_game_proto_LoginReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zzz_game_proto_LoginReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzz_game_proto_LoginResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zzz_game_proto_LoginResp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzz_game_proto_DrawLineReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zzz_game_proto_DrawLineReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzz_game_proto_DrawLineReq_point_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zzz_game_proto_DrawLineReq_point_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026DrawMessageProto.proto\022\022com.zzz.game.p" +
      "roto\"\030\n\010LoginReq\022\014\n\004name\030\001 \002(\t\"\027\n\tLoginR" +
      "esp\022\n\n\002id\030\001 \002(\005\"c\n\013DrawLineReq\0225\n\006points" +
      "\030\001 \003(\0132%.com.zzz.game.proto.DrawLineReq." +
      "point\032\035\n\005point\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zzz_game_proto_LoginReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zzz_game_proto_LoginReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zzz_game_proto_LoginReq_descriptor,
              new java.lang.String[] { "Name", });
          internal_static_com_zzz_game_proto_LoginResp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_zzz_game_proto_LoginResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zzz_game_proto_LoginResp_descriptor,
              new java.lang.String[] { "Id", });
          internal_static_com_zzz_game_proto_DrawLineReq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_zzz_game_proto_DrawLineReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zzz_game_proto_DrawLineReq_descriptor,
              new java.lang.String[] { "Points", });
          internal_static_com_zzz_game_proto_DrawLineReq_point_descriptor =
            internal_static_com_zzz_game_proto_DrawLineReq_descriptor.getNestedTypes().get(0);
          internal_static_com_zzz_game_proto_DrawLineReq_point_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zzz_game_proto_DrawLineReq_point_descriptor,
              new java.lang.String[] { "X", "Y", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
