// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TypeMessageEnumProto.proto

package com.zzz.game.proto;

public final class TypeMessageEnumProto {
  private TypeMessageEnumProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.zzz.game.proto.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN = 1;</code>
     *
     * <pre>
     *登录
     * </pre>
     */
    LOGIN(0, 1),
    /**
     * <code>DRAW_LINE = 2;</code>
     *
     * <pre>
     *划线
     * </pre>
     */
    DRAW_LINE(1, 2),
    /**
     * <code>DRAW_RECT = 3;</code>
     *
     * <pre>
     *花矩形
     * </pre>
     */
    DRAW_RECT(2, 3),
    /**
     * <code>USER_MESSAGE = 4;</code>
     *
     * <pre>
     *用户说话
     * </pre>
     */
    USER_MESSAGE(3, 4),
    /**
     * <code>DRAW_PLAYER = 5;</code>
     *
     * <pre>
     *谁画画
     * </pre>
     */
    DRAW_PLAYER(4, 5),
    /**
     * <code>TIME_COUNT = 6;</code>
     *
     * <pre>
     *开始倒计时
     * </pre>
     */
    TIME_COUNT(5, 6),
    ;

    /**
     * <code>LOGIN = 1;</code>
     *
     * <pre>
     *登录
     * </pre>
     */
    public static final int LOGIN_VALUE = 1;
    /**
     * <code>DRAW_LINE = 2;</code>
     *
     * <pre>
     *划线
     * </pre>
     */
    public static final int DRAW_LINE_VALUE = 2;
    /**
     * <code>DRAW_RECT = 3;</code>
     *
     * <pre>
     *花矩形
     * </pre>
     */
    public static final int DRAW_RECT_VALUE = 3;
    /**
     * <code>USER_MESSAGE = 4;</code>
     *
     * <pre>
     *用户说话
     * </pre>
     */
    public static final int USER_MESSAGE_VALUE = 4;
    /**
     * <code>DRAW_PLAYER = 5;</code>
     *
     * <pre>
     *谁画画
     * </pre>
     */
    public static final int DRAW_PLAYER_VALUE = 5;
    /**
     * <code>TIME_COUNT = 6;</code>
     *
     * <pre>
     *开始倒计时
     * </pre>
     */
    public static final int TIME_COUNT_VALUE = 6;


    public final int getNumber() { return value; }

    public static MessageType valueOf(int value) {
      switch (value) {
        case 1: return LOGIN;
        case 2: return DRAW_LINE;
        case 3: return DRAW_RECT;
        case 4: return USER_MESSAGE;
        case 5: return DRAW_PLAYER;
        case 6: return TIME_COUNT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zzz.game.proto.TypeMessageEnumProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.zzz.game.proto.MessageType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032TypeMessageEnumProto.proto\022\022com.zzz.ga" +
      "me.proto*i\n\013MessageType\022\t\n\005LOGIN\020\001\022\r\n\tDR" +
      "AW_LINE\020\002\022\r\n\tDRAW_RECT\020\003\022\020\n\014USER_MESSAGE" +
      "\020\004\022\017\n\013DRAW_PLAYER\020\005\022\016\n\nTIME_COUNT\020\006"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
